# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
